/// <reference types="node" />

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use Neon's direct endpoint. The app uses DATABASE_URL through
    // PrismaPg, which should be Neon's pooled endpoint on Vercel.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"]!,
  },
});
